version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyectdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      #- ./data/mysql:/var/lib/mysql# esto es si lo quisiera en una carpeta

  backend:
    build: ./Sistema_Reservas
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/proyectdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"
  servicio_correos:
    build:
      context: ./SR_Servicio_Correos
      dockerfile: Dockerfile
    container_name: SR_Servicio_Correos
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    networks:
      - app-network


  servicio_habitaciones:
    build:
      context: ./SR_Servicio_Habitaciones
      dockerfile: Dockerfile
    container_name: SR_Servicio_Habitaciones
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
    networks:
      - app-network

  servicio_pisos:
    build:
      context: ./SR_Servicio_Pisos
      dockerfile: Dockerfile
    container_name: SR_Servicio_Pisos
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
    networks:
      - app-network


  servicio_soap:
    build:
      context: ./SR_Servicio_SOAP_Reserva
      dockerfile: Dockerfile
    container_name: SR_Servicio_SOAP_Reserva
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq
    networks:
      - app-network


  servicio_tipohabitacion:
    build:
      context: ./SR_Servicio_TipoHabitacion
      dockerfile: Dockerfile
    container_name: SR_Servicio_TipoHabitacion
    ports:
      - "8084:8084"
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"     # Puerto para conexión de apps (AMQP)
      - "15672:15672"   # Puerto para el panel web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  servicio_alerts_login:
    build:
      context: ./Microservicio_Notificaciones_SpringBoot
      dockerfile: Dockerfile
    container_name: Microservicio_Notificaciones_SpringBoot
    ports:
      - "8086:8086"
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"     # Puerto para conexión de apps (AMQP)
      - "15672:15672"   # Puerto para el panel web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      
volumes:
  db_data:
